using Nueyon.Compose.Domain;

namespace Nueyon.Compose.Application.Agents;

/// <summary>
///     A deterministic fake IDEA agent that always returns the same example idea.
///     Used for testing the flow architecture without requiring a real LLM.
/// </summary>
public sealed class FakeIdeaAgent : IAgent<ChatInput, IReadOnlyList<Idea>>
{
    /// <summary>
    ///     Executes the fake agent by returning a single deterministic example idea.
    /// </summary>
    /// <param name="input">The chat input (not used by the fake agent).</param>
    /// <param name="cancellationToken">The cancellation token.</param>
    /// <returns>A read-only list containing exactly one example idea.</returns>
    public Task<IReadOnlyList<Idea>> ExecuteAsync(
        ChatInput input,
        CancellationToken cancellationToken = default)
    {
        ArgumentNullException.ThrowIfNull(input);

        var exampleIdea = new Idea
        {
            Title = "Example Idea",
            Description = "An example idea generated by the temporary fake agent.",
            Audience = "Test Audience",
            Rationale = "Used to verify the StoryFlow Idea stage."
        };

        var ideas = new List<Idea> { exampleIdea }.AsReadOnly();
        return Task.FromResult<IReadOnlyList<Idea>>(ideas);
    }
}