using System.Text.Json;
using Microsoft.Agents.AI;
using Nueyon.Compose.Domain;

namespace Nueyon.Compose.Application.Agents;

/// <summary>
/// A real IDEA agent powered by Microsoft Agent Framework and OpenAI.
/// Transforms a user's idea or thought into one or more concrete content ideas.
/// </summary>
public sealed class IdeaAgent : IAgent<ChatInput, IReadOnlyList<Idea>>
{
    private readonly AIAgent _agent;

    /// <summary>
    /// System instruction for the IDEA agent that guides its behavior.
    /// </summary>
    private const string SystemInstruction = """
        You are the Idea Agent in Nueyon.Compose.

        Your job is to transform a user's idea or thought into one or more concrete content ideas.

        Generate useful, specific ideas rather than generic topics.

        Each idea must have:
        - a short title
        - a clear description
        - a specific target audience
        - a clear rationale explaining why the idea is worth pursuing

        Return only valid JSON.
        Do not use Markdown.
        Do not wrap the JSON in ``` fences.
        Do not include explanations outside the JSON.
        """;

    /// <summary>
    /// Initializes a new instance of the IdeaAgent with the specified AIAgent.
    /// </summary>
    /// <param name="agent">The Microsoft Agent Framework AIAgent to use for generating ideas.</param>
    /// <exception cref="ArgumentNullException">Thrown when agent is null.</exception>
    public IdeaAgent(AIAgent agent)
    {
        _agent = agent ?? throw new ArgumentNullException(nameof(agent));
    }

    /// <summary>
    /// Executes the IDEA agent to generate content ideas from the user's input.
    /// </summary>
    /// <param name="input">The chat input containing the user's idea or thought.</param>
    /// <param name="cancellationToken">The cancellation token to cancel the operation.</param>
    /// <returns>A read-only list of ideas generated by the agent.</returns>
    /// <exception cref="ArgumentNullException">Thrown when input is null.</exception>
    /// <exception cref="InvalidOperationException">Thrown when the agent response is not valid JSON.</exception>
    public async Task<IReadOnlyList<Idea>> ExecuteAsync(
        ChatInput input,
        CancellationToken cancellationToken = default)
    {
        ArgumentNullException.ThrowIfNull(input);

        var userMessage = $"""
            Create content ideas from this input:

            {input.Content}
            """;

        // Run the agent with the user message
        var response = await _agent.RunAsync(userMessage, session: null, options: null, cancellationToken);

        var responseText = ExtractResponseText(response);

        var ideas = ParseIdeasFromJson(responseText);

        return ideas;
    }

    /// <summary>
    /// Extracts the text content from the agent response.
    /// </summary>
    /// <param name="response">The agent response.</param>
    /// <returns>The extracted text content.</returns>
    private static string ExtractResponseText(AgentResponse response)
    {
        ArgumentNullException.ThrowIfNull(response);

        // Use the built-in Text property which concatenates all text content
        var text = response.Text;

        if (string.IsNullOrWhiteSpace(text))
        {
            throw new InvalidOperationException("Agent response does not contain text content.");
        }

        return text;
    }

    /// <summary>
    /// Parses the JSON response from the model into a list of Idea objects.
    /// </summary>
    /// <param name="json">The JSON string to parse.</param>
    /// <returns>A read-only list of parsed Idea objects.</returns>
    /// <exception cref="InvalidOperationException">Thrown when the JSON is not valid or cannot be deserialized.</exception>
    private static IReadOnlyList<Idea> ParseIdeasFromJson(string json)
    {
        if (string.IsNullOrWhiteSpace(json))
        {
            throw new InvalidOperationException("Agent response is empty.");
        }

        try
        {
            var options = new JsonSerializerOptions
            {
                PropertyNameCaseInsensitive = true
            };

            var ideas = JsonSerializer.Deserialize<List<Idea>>(json, options)
                ?? throw new InvalidOperationException("Deserialization resulted in null list.");

            return ideas.AsReadOnly();
        }
        catch (JsonException ex)
        {
            throw new InvalidOperationException(
                $"Failed to parse agent response as JSON: {ex.Message}",
                ex);
        }
    }
}
