using System.Text.Json;
using Microsoft.Agents.AI;
using Microsoft.Extensions.AI;
using Nueyon.Compose.Domain;

namespace Nueyon.Compose.Application.Agents;

/// <summary>
/// A real IDEA agent powered by Microsoft Agent Framework and OpenAI.
/// Transforms a user's idea or thought into one or more concrete content ideas.
/// </summary>
public sealed class IdeaAgent : IAgent<ChatInput, IReadOnlyList<Idea>>
{
    private readonly AIAgent _agent;

    /// <summary>
    /// Initializes a new instance of the IdeaAgent with the specified AIAgent.
    /// </summary>
    /// <param name="agent">The Microsoft Agent Framework AIAgent to use for generating ideas.</param>
    /// <exception cref="ArgumentNullException">Thrown when agent is null.</exception>
    public IdeaAgent(AIAgent agent)
    {
        _agent = agent ?? throw new ArgumentNullException(nameof(agent));
    }

    /// <summary>
    /// Executes the IDEA agent to generate content ideas from the user's input.
    /// Configures structured output to enforce the IdeaResponse JSON contract.
    /// </summary>
    /// <param name="input">The chat input containing the user's idea or thought.</param>
    /// <param name="cancellationToken">The cancellation token to cancel the operation.</param>
    /// <returns>A read-only list of ideas generated by the agent.</returns>
    /// <exception cref="ArgumentNullException">Thrown when input is null.</exception>
    /// <exception cref="InvalidOperationException">Thrown when the agent response is not valid JSON.</exception>
    public async Task<IReadOnlyList<Idea>> ExecuteAsync(
        ChatInput input,
        CancellationToken cancellationToken = default)
    {
        ArgumentNullException.ThrowIfNull(input);

        var userMessage = $"""
            Create content ideas from this input:

            {input.Content}
            """;

        // Run the agent with structured output options configured
        var options = CreateAgentRunOptions();
        var response = await _agent.RunAsync(userMessage, session: null, options: options, cancellationToken);

        var responseText = ExtractResponseText(response);

        var ideas = ParseIdeasFromJson(responseText);

        return ideas;
    }

    /// <summary>
    /// Creates AgentRunOptions configured for structured output using the IdeaResponse schema.
    /// </summary>
    /// <returns>Configured AgentRunOptions with structured response format.</returns>
    private static ChatClientAgentRunOptions CreateAgentRunOptions()
    {
        // Configure structured output through ChatOptions
        // This ensures the LLM returns JSON that matches the IdeaResponse schema
        var chatOptions = new ChatOptions();

        // Pass structured output schema through AdditionalProperties
        // The OpenAI adapter will use this to configure the OpenAI API request
        chatOptions.AdditionalProperties["StructuredOutputType"] = typeof(IdeaResponse);
        chatOptions.AdditionalProperties["StructuredOutputSchema"] = GetIdeaResponseJsonSchema();

        // Create ChatClientAgentRunOptions with the configured ChatOptions
        var options = new ChatClientAgentRunOptions(chatOptions);
        return options;
    }

    /// <summary>
    /// Gets the JSON schema for IdeaResponse structured output.
    /// </summary>
    /// <returns>The JSON schema string.</returns>
    private static string GetIdeaResponseJsonSchema()
    {
        return """
        {
          "type": "object",
          "properties": {
            "ideas": {
              "type": "array",
              "items": {
                "type": "object",
                "properties": {
                  "title": {
                    "type": "string",
                    "description": "A short title for the idea"
                  },
                  "description": {
                    "type": "string",
                    "description": "A clear description of the idea"
                  },
                  "audience": {
                    "type": "string",
                    "description": "The specific target audience for this idea"
                  },
                  "rationale": {
                    "type": "string",
                    "description": "Why this idea is worth pursuing"
                  }
                },
                "required": ["title", "description", "audience", "rationale"],
                "additionalProperties": false
              },
              "description": "Array of idea objects"
            }
          },
          "required": ["ideas"],
          "additionalProperties": false
        }
        """;
    }

    /// <summary>
    /// Extracts the text content from the agent response.
    /// </summary>
    /// <param name="response">The agent response.</param>
    /// <returns>The extracted text content.</returns>
    private static string ExtractResponseText(AgentResponse response)
    {
        ArgumentNullException.ThrowIfNull(response);

        // Use the built-in Text property which concatenates all text content
        var text = response.Text;

        if (string.IsNullOrWhiteSpace(text))
        {
            throw new InvalidOperationException("Agent response does not contain text content.");
        }

        return text;
    }

    /// <summary>
    /// Parses the JSON response from the model into a list of Idea objects.
    /// 
    /// The expected response format is:
    /// {
    ///   "ideas": [
    ///     {
    ///       "title": "...",
    ///       "description": "...",
    ///       "audience": "...",
    ///       "rationale": "..."
    ///     }
    ///   ]
    /// }
    /// </summary>
    /// <param name="json">The JSON string to parse.</param>
    /// <returns>A read-only list of parsed Idea objects.</returns>
    /// <exception cref="InvalidOperationException">Thrown when the JSON is not valid or cannot be deserialized.</exception>
    private static IReadOnlyList<Idea> ParseIdeasFromJson(string json)
    {
        if (string.IsNullOrWhiteSpace(json))
        {
            throw new InvalidOperationException("Agent response is empty.");
        }

        try
        {
            var options = new JsonSerializerOptions
            {
                PropertyNameCaseInsensitive = true
            };

            var response = JsonSerializer.Deserialize<IdeaResponse>(json, options)
                ?? throw new InvalidOperationException("Deserialization resulted in null response.");

            if (response.Ideas == null)
            {
                throw new InvalidOperationException("Response ideas property is null.");
            }

            return response.Ideas;
        }
        catch (JsonException ex)
        {
            throw new InvalidOperationException(
                $"Failed to parse agent response as JSON: {ex.Message}",
                ex);
        }
    }
}
