using System.Text.Json.Serialization;
using Nueyon.Compose.Domain;

namespace Nueyon.Compose.Application.Agents;

/// <summary>
/// The structured response format for the Idea Agent.
/// 
/// This DTO enforces the JSON structure returned by the OpenAI model:
/// 
/// {
///   "ideas": [
///     {
///       "title": "...",
///       "description": "...",
///       "audience": "...",
///       "rationale": "..."
///     }
///   ]
/// }
/// 
/// The wrapper object is intentional. It provides an explicit structured-output
/// contract at the LLM boundary, preventing the model from returning a bare array
/// or other unexpected shapes.
/// </summary>
public sealed class IdeaResponse
{
    /// <summary>
    /// The collection of ideas generated by the agent.
    /// </summary>
    [JsonPropertyName("ideas")]
    public required IReadOnlyList<Idea> Ideas { get; init; }
}
