using System.Text.Json;
using Anthropic;
using Anthropic.Core;
using Nueyon.Compose.Domain;

namespace Nueyon.Compose.Application.Agents;

/// <summary>
/// A real IDEA agent powered by Microsoft Agent Framework and Anthropic Claude Haiku 4.5.
/// Transforms a user's idea or thought into one or more concrete content ideas.
/// </summary>
public sealed class IdeaAgent : IAgent<ChatInput, IReadOnlyList<Idea>>
{
    private readonly AnthropicClient _client;

    /// <summary>
    /// System instruction for the IDEA agent that guides its behavior.
    /// </summary>
    private const string SystemInstruction = """
        You are the Idea Agent in Nueyon.Compose.

        Your job is to transform a user's idea or thought into one or more concrete content ideas.

        Generate useful, specific ideas rather than generic topics.

        Each idea must have:
        - a short title
        - a clear description
        - a specific target audience
        - a clear rationale explaining why the idea is worth pursuing

        Return only valid JSON.
        Do not use Markdown.
        Do not wrap the JSON in ``` fences.
        Do not include explanations outside the JSON.
        """;

    private const string Model = "claude-haiku-4-5";

    /// <summary>
    /// Initializes a new instance of the IdeaAgent with a new Anthropic client.
    /// The API key is read from the ANTHROPIC_API_KEY environment variable.
    /// </summary>
    /// <exception cref="InvalidOperationException">Thrown when ANTHROPIC_API_KEY environment variable is not set.</exception>
    public IdeaAgent()
    {
        var apiKey = Environment.GetEnvironmentVariable("ANTHROPIC_API_KEY");
        if (string.IsNullOrWhiteSpace(apiKey))
        {
            throw new InvalidOperationException(
                "ANTHROPIC_API_KEY environment variable is not set. Please set it before using IdeaAgent.");
        }

        var options = new ClientOptions
        {
            ApiKey = apiKey
        };

        _client = new AnthropicClient(options);
    }

    /// <summary>
    /// Initializes a new instance of the IdeaAgent with the specified Anthropic client.
    /// Used for testing purposes.
    /// </summary>
    /// <param name="client">The Anthropic client to use.</param>
    /// <exception cref="ArgumentNullException">Thrown when client is null.</exception>
    public IdeaAgent(AnthropicClient client)
    {
        _client = client ?? throw new ArgumentNullException(nameof(client));
    }

    /// <summary>
    /// Executes the IDEA agent to generate content ideas from the user's input.
    /// </summary>
    /// <param name="input">The chat input containing the user's idea or thought.</param>
    /// <param name="cancellationToken">The cancellation token to cancel the operation.</param>
    /// <returns>A read-only list of ideas generated by the agent.</returns>
    /// <exception cref="ArgumentNullException">Thrown when input is null.</exception>
    /// <exception cref="InvalidOperationException">Thrown when the agent response is not valid JSON.</exception>
    public async Task<IReadOnlyList<Idea>> ExecuteAsync(
        ChatInput input,
        CancellationToken cancellationToken = default)
    {
        ArgumentNullException.ThrowIfNull(input);

        var userMessage = $"""
            Create content ideas from this input:

            {input.Content}
            """;

        var response = await _client.Messages.CreateAsync(new Anthropic.MessageCreateParams
        {
            Model = Model,
            MaxTokens = 2048,
            System = SystemInstruction,
            Messages = new[]
            {
                new Anthropic.MessageParam
                {
                    Role = "user",
                    Content = userMessage
                }
            }
        }, cancellationToken);

        var responseText = response.Content.FirstOrDefault()?.Text ?? string.Empty;

        var ideas = ParseIdeasFromJson(responseText);

        return ideas;
    }

    /// <summary>
    /// Parses the JSON response from the model into a list of Idea objects.
    /// </summary>
    /// <param name="json">The JSON string to parse.</param>
    /// <returns>A read-only list of parsed Idea objects.</returns>
    /// <exception cref="InvalidOperationException">Thrown when the JSON is not valid or cannot be deserialized.</exception>
    private static IReadOnlyList<Idea> ParseIdeasFromJson(string json)
    {
        if (string.IsNullOrWhiteSpace(json))
        {
            throw new InvalidOperationException("Agent response is empty.");
        }

        try
        {
            var options = new JsonSerializerOptions
            {
                PropertyNameCaseInsensitive = true
            };

            var ideas = JsonSerializer.Deserialize<List<Idea>>(json, options)
                ?? throw new InvalidOperationException("Deserialization resulted in null list.");

            return ideas.AsReadOnly();
        }
        catch (JsonException ex)
        {
            throw new InvalidOperationException(
                $"Failed to parse agent response as JSON: {ex.Message}",
                ex);
        }
    }
}
