using Nueyon.Compose.Application.Agents;
using Nueyon.Compose.Application.Flow;
using Nueyon.Compose.Application.Harness;
using Nueyon.Compose.Domain;
using Xunit;

namespace Nueyon.Compose.Application.Tests.Flow;

public sealed class StoryFlowEngineTests
{
    /// <summary>
    /// Test 1: IDEA flow executes successfully with a valid StoryWorkspace.
    /// </summary>
    [Fact]
    public async Task ExecuteAsync_WithValidWorkspace_CompletesSuccessfully()
    {
        // Arrange
        var agent = new FakeIdeaAgent();
        var harness = new FakeIdeaHarness(agent);
        var engine = new StoryFlowEngine(harness);

        var input = new ChatInput { Content = "Test input" };
        var workspace = new StoryWorkspace { Input = input };

        // Act
        var result = await engine.ExecuteAsync(workspace);

        // Assert
        Assert.NotNull(result);
    }

    /// <summary>
    /// Test 2: IDEA flow populates the workspace with exactly one idea containing the correct values.
    /// </summary>
    [Fact]
    public async Task ExecuteAsync_PopulatesWorkspaceWithExactlyOneIdea()
    {
        // Arrange
        var agent = new FakeIdeaAgent();
        var harness = new FakeIdeaHarness(agent);
        var engine = new StoryFlowEngine(harness);

        var input = new ChatInput { Content = "Test input" };
        var workspace = new StoryWorkspace { Input = input };

        // Act
        var result = await engine.ExecuteAsync(workspace);

        // Assert
        Assert.NotNull(result.Ideas);
        Assert.Single(result.Ideas);

        var idea = result.Ideas[0];
        Assert.Equal("Example Idea", idea.Title);
        Assert.Equal("An example idea generated by the temporary fake agent.", idea.Description);
        Assert.Equal("Test Audience", idea.Audience);
        Assert.Equal("Used to verify the StoryFlow Idea stage.", idea.Rationale);
    }

    /// <summary>
    /// Test 3: Workspace input is passed unchanged to the harness.
    /// </summary>
    [Fact]
    public async Task ExecuteAsync_PassesWorkspaceInputToHarness()
    {
        // Arrange
        var capturedInput = default(ChatInput);
        var mockAgent = new CaptureInputAgent(input => capturedInput = input);
        var harness = new FakeIdeaHarness(mockAgent);
        var engine = new StoryFlowEngine(harness);

        var expectedInput = new ChatInput { Content = "Test input content" };
        var workspace = new StoryWorkspace { Input = expectedInput };

        // Act
        await engine.ExecuteAsync(workspace);

        // Assert
        Assert.NotNull(capturedInput);
        Assert.Equal(expectedInput.Content, capturedInput.Content);
        Assert.Same(expectedInput, capturedInput);
    }

    /// <summary>
    /// Test 4: Cancellation token is forwarded unchanged to the harness.
    /// </summary>
    [Fact]
    public async Task ExecuteAsync_ForwardsCancellationTokenToHarness()
    {
        // Arrange
        var capturedToken = default(CancellationToken);
        var mockAgent = new CaptureTokenAgent(token => capturedToken = token);
        var harness = new FakeIdeaHarness(mockAgent);
        var engine = new StoryFlowEngine(harness);

        var input = new ChatInput { Content = "Test input" };
        var workspace = new StoryWorkspace { Input = input };
        var expectedToken = new CancellationToken();

        // Act
        await engine.ExecuteAsync(workspace, expectedToken);

        // Assert
        Assert.Equal(expectedToken, capturedToken);
    }

    /// <summary>
    /// Test 5: Flow Engine depends on the harness to obtain the result.
    /// </summary>
    [Fact]
    public async Task ExecuteAsync_ObtainsResultThroughHarness()
    {
        // Arrange
        var harnessWasCalled = false;
        var testIdea = new Idea
        {
            Title = "Custom Idea",
            Description = "Custom description",
            Audience = "Custom audience",
            Rationale = "Custom rationale"
        };

        var mockAgent = new TestAgent(
            () =>
            {
                harnessWasCalled = true;
                return new List<Idea> { testIdea }.AsReadOnly();
            });

        var harness = new FakeIdeaHarness(mockAgent);
        var engine = new StoryFlowEngine(harness);

        var input = new ChatInput { Content = "Test input" };
        var workspace = new StoryWorkspace { Input = input };

        // Act
        var result = await engine.ExecuteAsync(workspace);

        // Assert
        Assert.True(harnessWasCalled, "The harness should have been called");
        Assert.Single(result.Ideas);
        Assert.Equal("Custom Idea", result.Ideas[0].Title);
    }

    /// <summary>
    /// Test 6: FakeIdeaAgent always returns the same deterministic idea.
    /// </summary>
    [Fact]
    public async Task FakeIdeaAgent_ReturnsDeterministicIdea()
    {
        // Arrange
        var agent = new FakeIdeaAgent();
        var input = new ChatInput { Content = "Any input" };

        // Act
        var result1 = await agent.ExecuteAsync(input);
        var result2 = await agent.ExecuteAsync(input);

        // Assert
        Assert.NotNull(result1);
        Assert.NotNull(result2);
        Assert.Single(result1);
        Assert.Single(result2);

        var idea1 = result1[0];
        var idea2 = result2[0];

        Assert.Equal(idea1.Title, idea2.Title);
        Assert.Equal(idea1.Description, idea2.Description);
        Assert.Equal(idea1.Audience, idea2.Audience);
        Assert.Equal(idea1.Rationale, idea2.Rationale);
    }

    /// <summary>
    /// Test helper agent that captures the input.
    /// </summary>
    private sealed class CaptureInputAgent : IAgent<ChatInput, IReadOnlyList<Idea>>
    {
        private readonly Action<ChatInput> _onInput;

        public CaptureInputAgent(Action<ChatInput> onInput)
        {
            _onInput = onInput;
        }

        public Task<IReadOnlyList<Idea>> ExecuteAsync(
            ChatInput input,
            CancellationToken cancellationToken = default)
        {
            _onInput(input);
            var idea = new Idea
            {
                Title = "Example Idea",
                Description = "An example idea generated by the temporary fake agent.",
                Audience = "Test Audience",
                Rationale = "Used to verify the StoryFlow Idea stage."
            };
            return Task.FromResult<IReadOnlyList<Idea>>(new List<Idea> { idea }.AsReadOnly());
        }
    }

    /// <summary>
    /// Test helper agent that captures the cancellation token.
    /// </summary>
    private sealed class CaptureTokenAgent : IAgent<ChatInput, IReadOnlyList<Idea>>
    {
        private readonly Action<CancellationToken> _onToken;

        public CaptureTokenAgent(Action<CancellationToken> onToken)
        {
            _onToken = onToken;
        }

        public Task<IReadOnlyList<Idea>> ExecuteAsync(
            ChatInput input,
            CancellationToken cancellationToken = default)
        {
            _onToken(cancellationToken);
            var idea = new Idea
            {
                Title = "Example Idea",
                Description = "An example idea generated by the temporary fake agent.",
                Audience = "Test Audience",
                Rationale = "Used to verify the StoryFlow Idea stage."
            };
            return Task.FromResult<IReadOnlyList<Idea>>(new List<Idea> { idea }.AsReadOnly());
        }
    }

    /// <summary>
    /// Test helper agent with custom behavior.
    /// </summary>
    private sealed class TestAgent : IAgent<ChatInput, IReadOnlyList<Idea>>
    {
        private readonly Func<IReadOnlyList<Idea>> _execute;

        public TestAgent(Func<IReadOnlyList<Idea>> execute)
        {
            _execute = execute;
        }

        public Task<IReadOnlyList<Idea>> ExecuteAsync(
            ChatInput input,
            CancellationToken cancellationToken = default)
        {
            return Task.FromResult(_execute());
        }
    }
}
