using Microsoft.Extensions.Logging;
using Nueyon.Compose.Application.Agents;
using Nueyon.Compose.Application.Flow;
using Nueyon.Compose.Application.Tests.Agents;
using Nueyon.Compose.Domain;
using Xunit;

namespace Nueyon.Compose.Application.Tests.Flow;

public sealed class StoryFlowEngineTests
{
    /// <summary>
    ///     Creates a no-op logger for testing.
    /// </summary>
    private static NoOpLogger<StoryFlowEngine> CreateTestLogger() => new();

    /// <summary>
    ///     Test 1: IDEA flow executes successfully with a valid StoryWorkspace.
    /// </summary>
    [Fact]
    public async Task ExecuteAsync_WithValidWorkspace_CompletesSuccessfully()
    {
        // Arrange
        var agent = new FakeIdeaAgent();
        var logger = CreateTestLogger();
        var engine = new StoryFlowEngine(agent, logger);

        var executionContext = new FlowExecutionContext(Guid.NewGuid());
        var input = new ChatInput { Content = "Test input" };
        var workspace = new StoryWorkspace { Input = input };

        // Act
        var result = await engine.ExecuteAsync(executionContext, workspace);

        // Assert
        Assert.NotNull(result);
    }

    /// <summary>
    ///     Test 2: IDEA flow populates the workspace with exactly one idea containing the correct values.
    /// </summary>
    [Fact]
    public async Task ExecuteAsync_PopulatesWorkspaceWithExactlyOneIdea()
    {
        // Arrange
        var agent = new FakeIdeaAgent();
        var logger = CreateTestLogger();
        var engine = new StoryFlowEngine(agent, logger);

        var executionContext = new FlowExecutionContext(Guid.NewGuid());
        var input = new ChatInput { Content = "Test input" };
        var workspace = new StoryWorkspace { Input = input };

        // Act
        var result = await engine.ExecuteAsync(executionContext, workspace);

        // Assert
        Assert.NotNull(result.Ideas);
        Assert.Single(result.Ideas);

        var idea = result.Ideas[0];
        Assert.Equal("Example Idea", idea.Title);
        Assert.Equal("An example idea generated by the temporary fake agent.", idea.Description);
        Assert.Equal("Test Audience", idea.Audience);
        Assert.Equal("Used to verify the StoryFlow Idea stage.", idea.Rationale);
    }

    /// <summary>
    ///     Test 3: Workspace input is passed unchanged to the agent.
    /// </summary>
    [Fact]
    public async Task ExecuteAsync_PassesWorkspaceInputToHarness()
    {
        // Arrange
        var capturedInput = default(ChatInput);
        var mockAgent = new CaptureInputAgent(input => capturedInput = input);
        var logger = CreateTestLogger();
        var engine = new StoryFlowEngine(mockAgent, logger);

        var executionContext = new FlowExecutionContext(Guid.NewGuid());
        var expectedInput = new ChatInput { Content = "Test input content" };
        var workspace = new StoryWorkspace { Input = expectedInput };

        // Act
        await engine.ExecuteAsync(executionContext, workspace);

        // Assert
        Assert.NotNull(capturedInput);
        Assert.Equal(expectedInput.Content, capturedInput.Content);
        Assert.Same(expectedInput, capturedInput);
    }

    /// <summary>
    ///     Test 4: Cancellation token is forwarded unchanged to the agent.
    /// </summary>
    [Fact]
    public async Task ExecuteAsync_ForwardsCancellationTokenToHarness()
    {
        // Arrange
        var capturedToken = CancellationToken.None;
        var mockAgent = new CaptureTokenAgent(token => capturedToken = token);
        var logger = CreateTestLogger();
        var engine = new StoryFlowEngine(mockAgent, logger);

        var executionContext = new FlowExecutionContext(Guid.NewGuid());
        var input = new ChatInput { Content = "Test input" };
        var workspace = new StoryWorkspace { Input = input };
        var expectedToken = CancellationToken.None;

        // Act
        await engine.ExecuteAsync(executionContext, workspace, expectedToken);

        // Assert
        Assert.Equal(expectedToken, capturedToken);
    }

    /// <summary>
    ///     Test 5: Flow Engine depends on the agent to obtain the result.
    /// </summary>
    [Fact]
    public async Task ExecuteAsync_ObtainsResultThroughHarness()
    {
        // Arrange
        var agentWasCalled = false;
        var testIdea = new Idea
        {
            Title = "Custom Idea",
            Description = "Custom description",
            Audience = "Custom audience",
            Rationale = "Custom rationale"
        };

        var mockAgent = new TestAgent(() =>
        {
            agentWasCalled = true;
            return new List<Idea> { testIdea }.AsReadOnly();
        });

        var logger = CreateTestLogger();
        var engine = new StoryFlowEngine(mockAgent, logger);

        var executionContext = new FlowExecutionContext(Guid.NewGuid());
        var input = new ChatInput { Content = "Test input" };
        var workspace = new StoryWorkspace { Input = input };

        // Act
        var result = await engine.ExecuteAsync(executionContext, workspace);

        // Assert
        Assert.True(agentWasCalled, "The agent should have been called");
        Assert.Single(result.Ideas);
        Assert.Equal("Custom Idea", result.Ideas[0].Title);
    }

    /// <summary>
    ///     Test 6: FakeIdeaAgent always returns the same deterministic idea.
    /// </summary>
    [Fact]
    public async Task FakeIdeaAgent_ReturnsDeterministicIdea()
    {
        // Arrange
        var agent = new FakeIdeaAgent();
        var executionContext = new FlowExecutionContext(Guid.NewGuid());
        var input = new ChatInput { Content = "Any input" };

        // Act
        var result1 = await agent.ExecuteAsync(executionContext, input);
        var result2 = await agent.ExecuteAsync(executionContext, input);

        // Assert
        Assert.NotNull(result1);
        Assert.NotNull(result2);
        Assert.Single(result1);
        Assert.Single(result2);

        var idea1 = result1[0];
        var idea2 = result2[0];

        Assert.Equal(idea1.Title, idea2.Title);
        Assert.Equal(idea1.Description, idea2.Description);
        Assert.Equal(idea1.Audience, idea2.Audience);
        Assert.Equal(idea1.Rationale, idea2.Rationale);
    }

    /// <summary>
    ///     Test helper agent that captures the input.
    /// </summary>
    private sealed class CaptureInputAgent(Action<ChatInput> onInput) : IAgent<ChatInput, IReadOnlyList<Idea>>
    {
        public Task<IReadOnlyList<Idea>> ExecuteAsync(
            FlowExecutionContext executionContext,
            ChatInput input,
            CancellationToken cancellationToken = default)
        {
            ArgumentNullException.ThrowIfNull(executionContext);
            onInput(input);
            var idea = new Idea
            {
                Title = "Example Idea",
                Description = "An example idea generated by the temporary fake agent.",
                Audience = "Test Audience",
                Rationale = "Used to verify the StoryFlow Idea stage."
            };
            return Task.FromResult<IReadOnlyList<Idea>>(new List<Idea> { idea }.AsReadOnly());
        }
    }

    /// <summary>
    ///     Test helper agent that captures the cancellation token.
    /// </summary>
    private sealed class CaptureTokenAgent(Action<CancellationToken> onToken) : IAgent<ChatInput, IReadOnlyList<Idea>>
    {
        public Task<IReadOnlyList<Idea>> ExecuteAsync(
            FlowExecutionContext executionContext,
            ChatInput input,
            CancellationToken cancellationToken = default)
        {
            ArgumentNullException.ThrowIfNull(executionContext);
            onToken(cancellationToken);
            var idea = new Idea
            {
                Title = "Example Idea",
                Description = "An example idea generated by the temporary fake agent.",
                Audience = "Test Audience",
                Rationale = "Used to verify the StoryFlow Idea stage."
            };
            return Task.FromResult<IReadOnlyList<Idea>>(new List<Idea> { idea }.AsReadOnly());
        }
    }

    /// <summary>
    ///     Test helper agent with custom behavior.
    /// </summary>
    private sealed class TestAgent(Func<IReadOnlyList<Idea>> execute) : IAgent<ChatInput, IReadOnlyList<Idea>>
    {
        public Task<IReadOnlyList<Idea>> ExecuteAsync(
            FlowExecutionContext executionContext,
            ChatInput input,
            CancellationToken cancellationToken = default)
        {
            ArgumentNullException.ThrowIfNull(executionContext);
            return Task.FromResult(execute());
        }
    }

    /// <summary>
    ///     No-op logger for testing.
    /// </summary>
    private sealed class NoOpLogger<T> : ILogger<T>
    {
        public IDisposable? BeginScope<TState>(TState state) where TState : notnull => null;
        public bool IsEnabled(LogLevel logLevel) => false;

        public void Log<TState>(
            LogLevel logLevel,
            EventId eventId,
            TState state,
            Exception? exception,
            Func<TState, Exception?, string> formatter)
        {
            // No-op
        }
    }
}