using Nueyon.Compose.Application.Agents;
using Nueyon.Compose.Domain;

namespace Nueyon.Compose.Application.Harness;

/// <summary>
/// A fake implementation of the agent harness that delegates to a fake IDEA agent.
/// Used for testing the flow architecture without requiring a real agent or LLM.
/// </summary>
public sealed class FakeIdeaHarness : IAgentHarness<ChatInput, IReadOnlyList<Idea>>
{
    private readonly IAgent<ChatInput, IReadOnlyList<Idea>> _agent;

    /// <summary>
    /// Initializes a new instance of the FakeIdeaHarness with the specified agent.
    /// </summary>
    /// <param name="agent">The agent to delegate execution to.</param>
    /// <exception cref="ArgumentNullException">Thrown when agent is null.</exception>
    public FakeIdeaHarness(IAgent<ChatInput, IReadOnlyList<Idea>> agent)
    {
        _agent = agent ?? throw new ArgumentNullException(nameof(agent));
    }

    /// <summary>
    /// Executes the IDEA agent by delegating to the injected agent.
    /// </summary>
    /// <param name="input">The chat input to process.</param>
    /// <param name="cancellationToken">The cancellation token.</param>
    /// <returns>A read-only list of ideas generated by the agent.</returns>
    public Task<IReadOnlyList<Idea>> ExecuteAsync(
        ChatInput input,
        CancellationToken cancellationToken = default)
    {
        return _agent.ExecuteAsync(input, cancellationToken);
    }
}
