using Nueyon.Compose.Application.Agents;
using Nueyon.Compose.Application.Validation;
using Nueyon.Compose.Domain;

namespace Nueyon.Compose.Application.Harness;

/// <summary>
/// A harness that executes an IdeaAgent with validation and retry logic.
/// 
/// The harness owns the control loop:
/// - Executes the agent
/// - Validates the result
/// - Retries on invalid results up to a maximum of 3 total attempts
/// - Throws InvalidOperationException if all attempts fail
/// 
/// This separation ensures that the harness controls reliability while the agent focuses on AI execution.
/// </summary>
public sealed class IdeaHarness : IAgentHarness<ChatInput, IReadOnlyList<Idea>>
{
    private const int MaxAttempts = 3;

    private readonly IAgent<ChatInput, IReadOnlyList<Idea>> _agent;
    private readonly IIdeaValidator _validator;

    /// <summary>
    /// Initializes a new instance of the IdeaHarness with the specified agent and validator.
    /// </summary>
    /// <param name="agent">The agent to execute for generating ideas.</param>
    /// <param name="validator">The validator to validate the generated ideas.</param>
    /// <exception cref="ArgumentNullException">Thrown when agent or validator is null.</exception>
    public IdeaHarness(
        IAgent<ChatInput, IReadOnlyList<Idea>> agent,
        IIdeaValidator validator)
    {
        ArgumentNullException.ThrowIfNull(agent);
        ArgumentNullException.ThrowIfNull(validator);

        _agent = agent;
        _validator = validator;
    }

    /// <summary>
    /// Executes the agent with validation and retry logic.
    /// 
    /// The harness will:
    /// 1. Validate the input
    /// 2. Execute the agent
    /// 3. Validate the result
    /// 4. Retry up to 3 times if validation fails
    /// 5. Throw InvalidOperationException if all attempts fail
    /// </summary>
    /// <param name="input">The chat input to process.</param>
    /// <param name="cancellationToken">The cancellation token to forward to the agent.</param>
    /// <returns>A read-only list of valid ideas generated by the agent.</returns>
    /// <exception cref="ArgumentNullException">Thrown when input is null.</exception>
    /// <exception cref="InvalidOperationException">Thrown when the agent fails to produce valid ideas after 3 attempts.</exception>
    public async Task<IReadOnlyList<Idea>> ExecuteAsync(
        ChatInput input,
        CancellationToken cancellationToken = default)
    {
        ArgumentNullException.ThrowIfNull(input);

        for (int attempt = 1; attempt <= MaxAttempts; attempt++)
        {
            var ideas = await _agent.ExecuteAsync(input, cancellationToken);

            if (_validator.IsValid(ideas))
            {
                return ideas;
            }
        }

        throw new InvalidOperationException(
            "Idea agent failed to produce valid ideas after 3 attempts.");
    }
}
